# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10964430fce82818fdf34ea9045dfa2cf8b09b2e11165b90a627a55733e1169b9f427ed23bd8f3f2ab354e832b86048c9aca37eb579a0ca7bc54aee71b8a4942

test:
  secret_key_base: c236cb87fd11a33f4749b3ad367bf4a3a88150cfbd7a868b6756ce64277da63808a9ba5db218f1f0841455e6e4da3b414a7eab1eae3e0f00f73699ad862b083c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
